# Generated by Django 4.1.3 on 2022-12-05 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_project', to='softdesk.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
