# Generated by Django 4.1.3 on 2022-12-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0007_remove_contributor_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('contributor', 'Contributor')], max_length=120),
        ),
    ]
