# Generated by Django 4.1.3 on 2022-12-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0008_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author_user',
            field=models.ForeignKey(help_text='Author user is not used in permissions', on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
