# Generated by Django 4.1.3 on 2023-01-02 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0009_alter_project_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='projects', through='softdesk.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
