# Generated by Django 4.1.3 on 2023-01-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0011_rename_contributors_project_contributor_users_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_contribution'),
        ),
    ]
