# Generated by Django 4.1.5 on 2023-01-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0012_contributor_unique_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='modified_by',
        ),
    ]
